displayName=Slayer Task Odds
author=Razza98
description=Find the best Slayer master for your chosen task with account-aware odds that include your levels, quests, unlocks, and synced block lists.
tags=slayer,tasks,master,odds,blocks,probability,task,calc,calculator
version=1.0.0
plugins=slayertaskodds.SlayerOddsPlugin
build=standard

