package slayertaskodds;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.InputStreamReader;
import java.lang.reflect.Proxy;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import net.runelite.api.Client;
import net.runelite.api.gameval.DBTableID;
import net.runelite.api.gameval.VarbitID;

/** Compare the Java engine with independent fixtures generated by the original Wiki Lua. */
public final class SlayerOddsVerification
{
    public static void main(String[] args) throws Exception
    {
        Map<SlayerMaster, List<SlayerTask>> tables = TaskData.load(new Gson());
        List<Fixture> fixtures;
        try (InputStreamReader reader = new InputStreamReader(
            SlayerOddsVerification.class.getResourceAsStream("/slayertaskodds/wiki-fixtures.json"), StandardCharsets.UTF_8))
        {
            fixtures = new Gson().fromJson(reader, new TypeToken<List<Fixture>>() { }.getType());
        }
        int comparisons = 0;
        for (Fixture fixture : fixtures)
        {
            PlayerState state = new PlayerState();
            state.stats.putAll(fixture.state.stats);
            state.quests.addAll(fixture.state.quests);
            state.unlocks.addAll(fixture.state.unlocks);
            state.other.addAll(fixture.state.other);
            for (String quest : fixture.state.quests) PlayerStateReader.quest(quest);
            Set<String> blocks = SlayerOdds.blocks(fixture.state.blocks.toArray(new String[0]));
            for (Map.Entry<SlayerMaster, Expected> master : fixture.results.entrySet())
            {
                for (Map.Entry<String, Double> task : master.getValue().chances.entrySet())
                {
                    SlayerOdds.Result actual = SlayerOdds.calculate(tables.get(master.getKey()), task.getKey(), blocks, state);
                    require(actual.totalWeight == master.getValue().totalWeight && Math.abs(actual.chance() - task.getValue()) < 1e-12,
                        fixture.label + " / " + master.getKey() + " / " + task.getKey() + ": " + actual.chance() + " expected " + task.getValue());
                    comparisons++;
                }
            }
            if (fixture.label.equals("reported-steve-setup"))
            {
                SlayerOdds.Result result = SlayerOdds.calculate(tables.get(SlayerMaster.NIEVE), "Abyssal demons", blocks, state);
                require(result.targetWeight == 9 && result.totalWeight == 222, "Steve regression denominator");
            }
        }
        for (List<SlayerTask> table : tables.values())
            for (SlayerTask task : table)
                require(SlayerTaskChoice.fromStoredValue(task.name) != null, "Missing dropdown choice: " + task.name);
        require(SlayerOdds.blocks("Aviansie", "AVIANSIES").size() == 1, "Legacy/config aliases");
        verifySync();
        System.out.println("PASS: " + comparisons + " Lua probability comparisons across " + fixtures.size() + " account scenarios; block sync and config checks passed.");
    }

    private static void verifySync()
    {
        Set<Integer> seen = new HashSet<>();
        Client client = (Client) Proxy.newProxyInstance(Client.class.getClassLoader(), new Class<?>[] {Client.class}, (proxy, method, args) -> {
            switch (method.getName())
            {
                case "getVarbitValue":
                    seen.add((Integer) args[0]);
                    return ((Integer) args[0]) == VarbitID.SLAYER_BLOCKED_NIEVE_1 ? 42 : 0;
                case "getDBRowsByValue":
                    require((Integer) args[0] == DBTableID.SlayerTask.ID && (Integer) args[1] == DBTableID.SlayerTask.COL_ID && (Integer) args[3] == 42, "Resolve creature ID, not DB row ID");
                    return Collections.singletonList(9876);
                case "getDBTableField":
                    require((Integer) args[0] == 9876, "Use resolved row");
                    return new Object[] {"Greater demons"};
                default: throw new UnsupportedOperationException(method.getName());
            }
        });
        List<SlayerTaskChoice> slots = BlockSync.read(client, SlayerMaster.NIEVE);
        require(slots.size() == 7 && slots.get(0) == SlayerTaskChoice.GREATER_DEMONS && slots.get(6) == SlayerTaskChoice.NONE, "Ordered slots, including empty diary slot");
        require(seen.contains(VarbitID.SLAYER_BLOCKED_NIEVE_DIARY), "Read diary slot");
        seen.clear();
        for (SlayerMaster master : SlayerMaster.values()) BlockSync.read(client, master);
        require(seen.size() == 56, "Distinct per-master block varbits");
        Client unavailable = (Client) Proxy.newProxyInstance(Client.class.getClassLoader(), new Class<?>[] {Client.class}, (proxy, method, args) -> {
            if (method.getName().equals("getVarbitValue")) return 42;
            if (method.getName().equals("getDBRowsByValue")) return Collections.emptyList();
            throw new UnsupportedOperationException(method.getName());
        });
        boolean failed = false;
        try { BlockSync.read(unavailable, SlayerMaster.NIEVE); }
        catch (IllegalStateException expected) { failed = true; }
        require(failed, "Unavailable task data must fail instead of clearing blocks");
        require(SlayerMaster.byGameId(6) == SlayerMaster.NIEVE && SlayerMaster.byGameId(3) == SlayerMaster.VANNAKA && SlayerMaster.byGameId(0) == null, "Master mapping");
        long slotsConfigured = Arrays.stream(SlayerOddsConfig.class.getDeclaredMethods()).filter(m -> m.getName().matches(".*Block[1-7]")).count();
        require(slotsConfigured == 56, "Seven config slots for eight masters");
    }

    private static void require(boolean condition, String message)
    {
        if (!condition) throw new AssertionError(message);
    }

    private static final class Fixture { String label; State state; Map<SlayerMaster, Expected> results; }
    private static final class State { Map<String, Integer> stats; List<String> quests, unlocks, other, blocks; }
    private static final class Expected { int totalWeight; Map<String, Double> chances; }
}
